version: '2'
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  app:
    ports:
      - 8081:8080
#    working_dir: /
    build: .
    depends_on:
      - mongodb
